name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 194.164.64.44
        username: u204807276.pawsarelost.com
        password: ${{ secrets.FTP_PASSWORD }}  # Set your FTP password as a secret
        local-dir: ./  # Path to your project folder (root of the repo)
        server-dir: /public_html/pawsarelost.com/  # This should point to public_html on your server